### ISSUE TITLE
OperationalError at /blog/ no such table: content_blog

### ISSUE THREAD

**Issue by ShariqAyaz** [mavenium/PyEditorial#11]
OperationalError at /blog/
no such table: content_blog

the following error i am facing

**Comment by mavenium** [comment]
The required information has already been entered in the [wiki section](https://github.com/mavenium/PyEditorial/wiki/no-such-table) and the [previous issue](https://github.com/mavenium/PyEditorial/issues/3). Please read the previous issue and wiki section before opening the issue.
