### ISSUE TITLE
Adding Postgresql as a DB ?

### ISSUE THREAD

**Issue by ribrea** [mavenium/PyEditorial#21]
In CRMs there are a lot of datastore and being fast is so important, I thought it would be great if we try to add PostgreSQL as a Database to the project and add a Setting to manage and switch between Database as:
````python
# in setting.py
# -- Snip
Postgres = True
if Postgres:
  DATABASES = {
      'default': {
          'ENGINE': 'django.db.backends.postgresql_psycopg2',
          'NAME': ‘<db_name>’,
          'USER': '<db_username>',
          'PASSWORD': '<password>',
          'HOST': '<db_hostname_or_ip>',
          'PORT': '<db_port>',
      }
  }
else:
  DATABASES = {
      'default': {
          'ENGINE': 'django.db.backends.sqlite3',
          'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
      }
  }

````
Also, we can add Postgres to Docker PR #20  
Let me know your opinion and if I can work on it.

###### AE

**Comment by Bhavyaseth-afk** [comment]
Have you added PostgreSQL? Do we need to create a Pull request for it? 
P.S I have just started contributing to Open source

**Comment by mavenium** [comment]
You must make the necessary changes to add PostgreSQL to a separate branch and then create a PUll request.

**Comment by Bhavyaseth-afk** [comment]
> You must make the necessary changes to add PostgreSQL to a separate branch and then create a PUll request.

Is the issue still open?
