### ISSUE TITLE
[Question] Why ignore migrations in version control?

### ISSUE THREAD

**Issue by GustavoCayres** [mavenium/PyEditorial#25]
Hi, guys!

When setting up the project, I realized that the app's migrations are not being committed, and we're actually instructing running
`python manage.py makemigrations` during setup.

Although it may seem irrelevant now to keep migrations in version control, after deploying a production database (or after multiple developers build their long lived databases), saving migrations will allow us to apply changes to our database without having to tear it down.

Was there a specific reason for .gitignoring migrations?

**Comment by mavenium** [comment]
Hello
In projects, migrations files become commite when changes have been made in them, or the order of execution of migrations files is important, or the project is being developed as a team.
