### ISSUE TITLE
no such table: content_blog

### ISSUE THREAD

**Issue by kyrrosanguine** [mavenium/PyEditorial#26]
It maybe an issue caused by me cause I'm not experienced. I followed the instrutions on  readme file accordingly (also migrated througly). When I ran the site it gave me " In template /home/melvinger/Desktop/editorial /PyEditorial-master/templates/base.html, error at line 0" in the debug with "no such table: content_blog". This error occured in admin page too when i tried to access admin/content/blog/ with "no such table: content_blogcategory) ". Tried to figure out the issue but cant.  I know its an old project still if you return i will be glad. 
![Screenshot from 2022-09-21 08-46-46](https://user-images.githubusercontent.com/78818040/191424113-e338978c-91c7-47b1-8b42-f490d9bee097.png)

**Comment by mavenium** [comment]
Please read the [closed issues](https://github.com/mavenium/PyEditorial/issues/3) and [wiki section](https://github.com/mavenium/PyEditorial/wiki/no-such-table) before opening a new request.
