### ISSUE TITLE
No such table: content_blog

### ISSUE THREAD

**Issue by farhadmpr** [mavenium/PyEditorial#3]
I could not run the project.
After executing the required commands, I get the following error when executing:
`no such table: content_blog`

**Comment by divyagar** [comment]
what is this command basically doing and why makemigrations is not working as expected.

**Comment by mavenium** [comment]
you can read more about this command in [this article](https://docs.djangoproject.com/en/3.2/ref/django-admin/).

**Comment by Deebling5** [comment]
> I have already run these commands but they were not created.
> This command solved the problem:
> `python manage.py migrate --run-syncdb`

Works like a charm after this. Hey Admin, you can update this in your ReadMe file.

**Comment by mavenium** [comment]
The required information has already been entered in the[ wiki section](https://github.com/mavenium/PyEditorial/wiki/no-such-table). Please read the previous issue and wiki section before opening the issue.
