### ISSUE TITLE
no such table: content_blog

### ISSUE THREAD

**Issue by C4SP5Anq** [mavenium/PyEditorial#44]
How can I solve this problem:
no such table: content_blog
thanks for your help
![image](https://github.com/user-attachments/assets/a17c01ca-28f4-48cd-bec8-b52d85e7e121)

**Comment by B1ng0OOO** [comment]
@mavenium

**Comment by ayeleworkm** [comment]
Have you figured out how to solve this problem?? I have the same problem.

**Comment by ayeleworkm** [comment]
@B1ng0OOO

**Comment by mavenium** [comment]
Have you ever read the wiki section ?!
https://github.com/mavenium/PyEditorial/wiki/no-such-table
