### ISSUE TITLE
Skill Icon Name

### ISSUE THREAD

**Issue by divyagar** [mavenium/PyEditorial#9]
What is the use of the Icon name column in skills section. How to use that column so that it will show proper icon as shown in the screenshots provided by you..

**Comment by mavenium** [comment]
The Editorial template provided by [HTML5UP](https://html5up.net/editorial) uses [Fontawesome](https://fontawesome.com/) to display icons. To display the icon, just enter the name of the icon you want in the icon field.
For example, `fa-gem` to display a diamond icon.
